name: Build and Deploy Pipeline2

on:
  workflow_dispatch:   # manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          echo "🔨 Building Docker image..."
          docker build -t amruthaachar08/myapp:latest .
          echo "📦 Pushing Docker image..."
          docker push amruthaachar08/myapp:latest
