name: Build and Deploy Pipeline2

on:
  workflow_dispatch:   # manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          echo "🔨 Building Docker image..."
          docker build -t amruthaachar08/myapp:latest .
          echo "📦 Pushing Docker image..."
          docker push amruthaachar08/myapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.35.1

      - name: Configure Kubeconfig
        run: |
          echo "⚙️ Setting up kubeconfig..."
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          echo "🚀 Restarting deployment..."
          kubectl set image deployment/myapp-deployment myapp=amruthaachar08/myapp:latest --record
          kubectl rollout status deployment/myapp-deployment
          echo "🌐 Current service URL:"
          kubectl get svc myapp-service -o jsonpath='{.spec.ports[0].nodePort}'
